SettingsInfo:
  x-acl:
    platformAdmin: [read-any]
    teamAdmin: [read-any]
    teamMember: [read-any]
  properties:
    cluster:
      properties:
        name:
          $ref: 'definitions.yaml#/clusterName'
        domainSuffix:
          $ref: 'definitions.yaml#/domainSuffix'
        apiServer:
          $ref: 'definitions.yaml#/url'
          title: API server
          description: URL to the Kubernetes API. Used to generate the KUBECONFIG for download, for direct access to the cluster.
        provider:
          $ref: 'definitions.yaml#/provider'
        linode:
          additionalProperties: false
          properties:
            tier:
              type: string
              description: Linode Kubernetes Engine tier (standard LKE or enterprise LKE-E)
              default: standard
              enum:
                - standard
                - enterprise
    dns:
      properties:
        zones:
          description: Extra DNS zones that the cluster can administer. Team services can use this to publish their URLs on.
          items:
            type: string
            title: Zone
          title: Zones
          type: array
          uniqueItems: true
    otomi:
      properties:
        hasExternalDNS:
          type: boolean
          default: false
        isPreInstalled:
          type: boolean
          default: false
        aiEnabled:
          type: boolean
          default: false
        hasExternalIDP:
          type: boolean
          default: false
        git:
          properties:
            repoUrl:
              type: string
              description: The base URL of the Git repository (without credentials).
              pattern: '^https?://.+'
            branch:
              type: string
              description: The branch to use in the Git repository.
    smtp:
      properties:
        smarthost:
          type: string
    ingressClassNames:
      description: Ingress class names that are used by the cluster.
      items:
        type: string
      type: array
      uniqueItems: true
  type: object
